version: '3.9'
services:
  mongodb:
    image: mongo:7.0.8
    restart: always
    volumes:
      - ./db-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ADMIN}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
        - "127.0.0.1:${MONGODB_PORT}:27017"
  app:
    build: .
    image: ad-placement-service-app
    depends_on:
      - redis-proxy
      - mongodb
    restart: always
    ports:
      - "127.0.0.1:${GIN_PORT}:3000"
  redis-node-1:
    image: redis:7.2.3
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: ["/tmp/build.sh", "$REDIS_HOST", "9001"]
    volumes:
      - ./config/redis/build.sh:/tmp/build.sh
  redis-node-2:
    image: redis:7.2.3
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: ["/tmp/build.sh", "$REDIS_HOST", "9002"]
    volumes:
      - ./config/redis/build.sh:/tmp/build.sh
  redis-node-3:
    image: redis:7.2.3
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: ["/tmp/build.sh", "$REDIS_HOST", "9003"]
    volumes:
      - ./config/redis/build.sh:/tmp/build.sh
  redis-node-4:
    image: redis:7.2.3
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: ["/tmp/build.sh", "$REDIS_HOST", "9004"]
    volumes:
      - ./config/redis/build.sh:/tmp/build.sh
  redis-node-5:
    image: redis:7.2.3
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: ["/tmp/build.sh", "$REDIS_HOST", "9005"]
    volumes:
      - ./config/redis/build.sh:/tmp/build.sh
  redis-node-6:
    image: redis:7.2.3
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: ["/tmp/build.sh", "$REDIS_HOST", "9006"]
    volumes:
      - ./config/redis/build.sh:/tmp/build.sh
  redis-cluster-creator:
    image: redis:7.2.3
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDISCLI_AUTH: ${REDIS_PASSWORD}
    command: "redis-cli --cluster create $REDIS_HOST:9001 $REDIS_HOST:9002 $REDIS_HOST:9003 $REDIS_HOST:9004 $REDIS_HOST:9005 $REDIS_HOST:9006 --cluster-replicas 1 --cluster-yes"
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
      - redis-proxy
  redis-proxy:
    image: haproxy:3.0-dev6-alpine3.19
    volumes:
      - ./config/haproxy:/usr/local/etc/haproxy:ro
    ports:
      - "8404:8404"
      - "9001-9006:9001-9006"
      - "9101-9106:9101-9106"
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
  redis-insight:
    image: redislabs/redisinsight:1.14.0
    ports:
      - "127.0.0.1:8001:8001"
    depends_on:
      - redis-proxy
